### ISSUE TITLE
Not downloading certain posts through Subreddit link but will download when given link to single post

### ISSUE THREAD

**Issue by ghost** [ripmeapp2/ripme#54]
* Ripme version: v2.0.1
* Java version:
* java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
* Operating system: Windows 10 [Version 10.0.19043.1348]
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/RWBYNSFW/comments/amvtji/mega_monochrome_album_dashingicecream/

When ripping https://www.reddit.com/r/RWBYNSFW/new/, I noticed that some posts were not showing up in the save directory, such as the link above. Even after multiple re-rips, it is not showing up.

## Expected Behavior

Rip Imgur album from Reddit through subreddit link

## Actual Behavior

Post skipped and not downloaded (when given the post link as a source (instead of the full subreddit), it is downloaded correctly)

**Comment by NachtOff** [comment]
So I dug around a bit and I think I figured out what happened. Reddit will only load so many posts into a view. It looks like it's around 1,000 (at least in this case, might be different for different subs, I don't know). That only goes back about 3-4 months instead of the three years to get to the post linked. Really crappy limitation imo

**Comment by madhatr** [comment]
This is a limitation in the reddit api.  Nothing to due with ripme.  I believe some downloaders have developed certain way to get around the 1000 limit but I have not looked into it.
